# Generated by Django 5.2.18 on 2026-10-08 16:19

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(default='Afrobeats', max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('audio_file', models.FileField(upload_to='beats/audio/%Y/%m/')),
                ('cover_image', models.FileField(blank=True, upload_to='beats/covers/%Y/%m/')),
                ('bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('musical_key', models.CharField(blank=True, max_length=24)),
                ('tag', models.CharField(blank=True, max_length=36)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(blank=True, upload_to='videos/%Y/%m/')),
                ('video_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('DEMO', 'Demo only')], default='PENDING', max_length=10)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile money'), ('bank', 'Bank / card')], max_length=24)),
                ('payment_reference', models.CharField(default=store.models.make_payment_reference, max_length=64, unique=True)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=64)),
                ('payment_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.beat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
