# Generated by Django 5.2.18 on 2026-10-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='preview_file',
            field=models.FileField(blank=True, upload_to='beats/previews/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='audio_file',
            field=models.FileField(upload_to='beats/private/%Y/%m/'),
        ),
    ]
